### ISSUE TITLE
Create commands for comparing and copying values over two environments

### ISSUE THREAD

**Issue by ghost** [motns/configstore#1]
It would be great if there was a functionality that allows to copy values from one environment to another. 

For example, we defined two environments `prod` and `disaster_recovery`. Both of them are encrypted using different KMS keys. We could have a command that takes values from `prod` and copies them over to `disaster_recovery`. Values in the latter one need to be decrypted and encrypted for the new environment.

What's more, it would be great if optionally:
- some keys can be excluded from copying;
- or the other way, keys to copied over can be defined;
- additional keys can be added/overwritten;
- certain keys can be converted from being encrypted to be decrypted (and the other way).

The functionality is very useful when one environment is "based" on another.

There is a Python script that does that called; it's called confy and can be found [here](https://github.com/nicholasgasior/confy). Though, I was wondering if we could implement that to Configstore.

**Comment by motns** [comment]
@mikolajgasior FYI. I've added support for copying in Release 2.3.0: https://github.com/motns/configstore/releases/tag/v2.3.0
This can either copy all keys or just a subset of them, defined via a pattern. There are also a couple of new commands for individually toggling values between secret and plain.
This sits nicely on top of existing functionality, and doesn't do anything too complicated or magical.

We can have a conversation around whether we need to add any more functionality to cover your use case, but my feeling is:
* Configstore environments have to contain the exact same keys, so it's probably not a good idea to allow people to introduce new keys *during a copy operation*
* I'm not sure there's a use case for changing the `is_secret` flag on a value while copying it from one environment to another - do you have an example?
* `configstore package tree` covers some of your diff functionality already - it highlights missing keys, and allows you to eyeball how values for a given key differ in various top-level and sub-environments. We could expand this further to exclude keys that have the same value in all environments.

Did I miss something from the above list?

**Comment by motns** [comment]
@mikolajgasior I've just released version 2.4.0: https://github.com/motns/configstore/releases/tag/v2.4.0
This adds a few more commands to cover what you're describing above:
* `configstore copy` now has a `--recursive` option  to copy nested sub-environments, and a `--skip-existing` option to ignore keys that exist in the destination while copying
* There's a new `configstore diff` command for comparing two environments

I think this pretty much covers everything you need, so let me know if we're good to close this ticket.

**Comment by ghost** [comment]
@motns Thanks for the functionality. Now, I'm able to copy over configuration values between environments, and I got environments reduced by replacing most of them with sub-environments. 

As for few questions you had there in earlier comment... 
In terms of changing a key from being secret to not being one, I had some values that were encrypted and they shouldn't really be. But, this is no longer the case as the same keys in a project should be secret in all environments.
It's good to not introduce a new key during _copy_ operation. Good call, it could be confusing. In the end, you just initialise your environment first and then copy values to it.
And finally, new `configstore diff` and `configstore package tree` are good enough.

I believe I can remove all the magic scripts I had to write to deal with that kind of stuff. Brilliant, great work!

I will close the issue.
